language: ruby
rvm:
  - 2.2.0
env:
  global:
    secure: Z13+aajF3Ryp87S+y2MnPB62M+MgILVwRcs95ptt8weXHjV5cTVBIwzv1IS4BWtCPnXs7cL9r9NXOdMFSjsaM96aDoGnR7Tlo2o1aoTabvQ0s53N2gY9/vuhbqHGrcduWdP/eQo1oJg4gI8WUn3XyfJYh45rZ0Vkfi68LXhqlu0vvE1wNV7+iemTc4oj99y85cWUxw5ZbaNRGPRIk3jLcINUxJTFvOb7H9w3319Ur1OXj1EIuW442+PzLaBQGd+E9cIFD54w7vXJYODJLOJjJc3OF+sw/RL20X/lzLaSVEtsFuVhXOpjhxqUj1RX1H8kdtBuorOGg/M2qKy5xcDvm8pWvzpqhA9XrBxunCvyfqFcae2kwcB94Sq4Pb5sfMXTmYXjkjq3TiOesbks9HKHs5F3p69R3n0gJk9K8dAdPnP/pXyr3VhcE2MBOhUyokGAgnkOGwAcoqyKeq+/FAsH9+9ADvNWmdG5WKaWw+YXFTDLLtoirfQHM1zvodGfqFDi2FHvd9buDUiIPuQFcBThmoUhBJMRiG1KLDcgNJzLGQFN2Xp4g0KQyudOt5bWeWBpvDVEpYImvKmzUQTCDYPZ0HJcXdid9/CDwwgyJHN5MhTewx421WYU1jNCilvGea2zhoi3FyX+QGLzKz6UJ1Mb7hgQgE1HHNPRuWHk45MhOqU=
before_install:
  - curl -fsSL https://mackerel.io/assets/files/scripts/setup-apt.sh | sudo sh
  - sudo apt-get update -qq
  - sudo apt-get install mkr
