version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
    steps:
      - checkout
      - run: 
          name: Set up a package repository for mackrel commands
          command: curl -fsSL https://mackerel.io/assets/files/scripts/setup-apt.sh | sudo sh
      - run: sudo apt-get update -qq
      - run: sudo apt-get install mkr
  test:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
    steps:
      - checkout
      - run: rake
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
        requires:
          - build