version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
    working_directory: ~/repo
    steps:
      - checkout
      - run: 
          name: Set up a package repository for mackrel commands
          command: curl -fsSL https://mackerel.io/assets/files/scripts/setup-apt.sh | sudo sh
      - run: sudo apt-get update -qq
      - run:
          name: Install mkr command
          command: sudo apt-get install mkr
      - run:
          name: Run tests
          command: rake